// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FvEKaYzTksbVHtrNMrho834TYKaSUiQ',
    appId: '1:756011732069:web:496ee7b0f07aa0e3e90a8c',
    messagingSenderId: '756011732069',
    projectId: 'fir-001-6844b',
    authDomain: 'fir-001-6844b.firebaseapp.com',
    storageBucket: 'fir-001-6844b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrIYS8HBB7yBRPLQ4dfdFJAtSJGpFnsn8',
    appId: '1:756011732069:android:1479b150d274d5f4e90a8c',
    messagingSenderId: '756011732069',
    projectId: 'fir-001-6844b',
    storageBucket: 'fir-001-6844b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-t46AU_nUhAdcqPYPAkcHc-7G1Y2FNfA',
    appId: '1:756011732069:ios:fee2e20b698da173e90a8c',
    messagingSenderId: '756011732069',
    projectId: 'fir-001-6844b',
    storageBucket: 'fir-001-6844b.appspot.com',
    iosClientId: '756011732069-8lr5nson5dfqo7q08kn8i6a3mf12ekma.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-t46AU_nUhAdcqPYPAkcHc-7G1Y2FNfA',
    appId: '1:756011732069:ios:fee2e20b698da173e90a8c',
    messagingSenderId: '756011732069',
    projectId: 'fir-001-6844b',
    storageBucket: 'fir-001-6844b.appspot.com',
    iosClientId: '756011732069-8lr5nson5dfqo7q08kn8i6a3mf12ekma.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
